service: laravel

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: ap-southeast-1
  # Environment variables
  environment:
    APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
    #ASSET_URL: !Sub 'https://${AssetsCdn.DomainName}'
    ASSET_URL: !Sub 'https://ken-assets.${ssm:/ken/route53/zoneName}'
    SQS_PREFIX: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}'
    DB_CONNECTION: mysql
    DB_HOST: ${ssm:/ken/rds/host}
    DB_PORT: ${ssm:/ken/rds/port}
    DB_DATABASE: ${ssm:/ken/rds/database}
    DB_USERNAME: ${ssm:/ken/rds/username}
    DB_PASSWORD: ${ssm:/ken/rds/password}
  iam:
    role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-laravel-role'

custom:
  s3Sync:
    # Sync public directory to the assets S3 bucket
    - bucketName: ken-laravel-static-assets
      localDir: public
      deleteRemoved: true
      acl: public-read
    # The example above will upload index.php to S3 bucket too.
    # - bucketName: ken-laravel-static-assets
    #   prefix: css
    #   localDir: public/css
    #   deleteRemoved: true
    #   acl: public-read
  prune:
    automatic: true
    number: 3

package:
  exclude:
    - public/**
    - node_modules/**
    - resources/assets/**
    - storage/**
    - tests/**
  # Files and directories to exclude from deployment
  include:
    - public/index.php
    - public/robots.txt
    - public/favicon.ico
    - app/**
    - bootstrap/**
    - config/**
    - routes/**
    - vendor/**
    - artisan

functions:

  # This function runs the Laravel website/API
  web:
    handler: public/index.php
    runtime: php-81-fpm
    architecture: arm64
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: '*'
    vpc:
      securityGroupIds: ${ssm:/ken/bref/securityGroupIds}
      subnetIds: ${ssm:/ken/bref/privateSubnetIds}

    # This function lets us run artisan commands in Lambda
  artisan:
      handler: artisan
      runtime: php-81-console
      architecture: arm64
      timeout: 720 # in seconds
      # Uncomment to also run the scheduler every minute
      events:
        - schedule:
            rate: rate(30 minutes)
            input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - serverless-s3-sync
  - serverless-prune-plugin

resources:
  Mappings: 
    CachePolicyIds:
      # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
      Amplify:
        Id: 2e54312d-136d-493c-8eb9-b001f22f67d2
      CachingDisabled:
        Id: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
      CachingOptimized:
        Id: 658327ea-f89d-4fab-a63d-7e88639e58f6
      CachingOptimizedForUncompressedObjects:
        Id: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
      Elemental-MediaPackage:
        Id: 08627262-05a9-4f76-9ded-b50ca2e3a84f
    OriginRequestPolicyIds:
      # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
      AllViewer:
        Id: 216adef6-5c7f-47e4-b989-5492eafa07d3
      AllViewerAndCloudFrontHeaders-2022-06:
        Id: 33f36d7e-f396-46d9-90e0-52428a34d9dc
      AllViewerExceptHostHeader:
        Id: b689b0a8-53d0-40ab-baf2-68738e2966ac
      CORS-CustomOrigin:
        Id: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
      Elemental-MediaTailor-PersonalizedManifests:
        Id: 775133bc-15f2-49f9-abea-afb2e0bf67d2
      UserAgentRefererHeaders:
        Id: acba4595-bd28-49b8-b9fe-13317c0390fa
    ResponseHeadersPolicyIds:
      # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html
      CORS-and-SecurityHeadersPolicy:
        Id: e61eb60c-9c35-4d20-a928-2b84e02af89c
      CORS-With-Preflight:
        Id: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
      CORS-with-preflight-and-SecurityHeadersPolicy:
        Id: eaab4381-ed33-4a86-88ca-d9558dc6cd63
      SecurityHeadersPolicy:
        Id: 67f7725c-6f97-4210-82d7-5512b31e9d03
      SimpleCORS:
        Id: 60669652-455b-4ae9-85a4-c4c02393f86c
  Resources:
    SiteCdn:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Aliases:
            - !Sub 'ken-site.${ssm:/ken/route53/zoneName}'
          ViewerCertificate:
            AcmCertificateArn: ${ssm:/ken/acm/usEast1Arn}
            MinimumProtocolVersion: TLSv1
            SslSupportMethod: sni-only
          PriceClass: PriceClass_100
          HttpVersion: http2
          Origins:
            - Id: HttpApi
              DomainName: !Sub '${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
              CustomOriginConfig: 
                OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            AllowedMethods: [GET, HEAD]
            TargetOriginId: HttpApi
            CachePolicyId: !FindInMap [ CachePolicyIds, CachingOptimized , Id ]
            OriginRequestPolicyId: !FindInMap [ OriginRequestPolicyIds, AllViewerExceptHostHeader, Id ]
            ResponseHeadersPolicyId: !FindInMap [ ResponseHeadersPolicyIds, CORS-with-preflight-and-SecurityHeadersPolicy, Id ]
            ViewerProtocolPolicy: redirect-to-https
    SiteDns:
      Type: 'AWS::Route53::RecordSet'
      Properties:
        HostedZoneId: ${ssm:/ken/route53/zoneId}
        Name: !Sub 'ken-site.${ssm:/ken/route53/zoneName}'
        Type: A
        AliasTarget:
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt SiteCdn.DomainName
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ken-laravel-static-assets
    AssetsCdn:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Aliases:
            - !Sub 'ken-assets.${ssm:/ken/route53/zoneName}'
          ViewerCertificate:
            AcmCertificateArn: ${ssm:/ken/acm/usEast1Arn}
            MinimumProtocolVersion: TLSv1
            SslSupportMethod: sni-only
          PriceClass: PriceClass_100
          HttpVersion: http2
          Origins:
            - Id: AssetsBucket
              DomainName: !GetAtt AssetsBucket.RegionalDomainName
              S3OriginConfig: {}
          DefaultCacheBehavior:
            AllowedMethods: [GET, HEAD]
            TargetOriginId: AssetsBucket
            CachePolicyId: !FindInMap [ CachePolicyIds, CachingOptimized , Id ]
            OriginRequestPolicyId: !FindInMap [ OriginRequestPolicyIds, AllViewerExceptHostHeader, Id ]
            ResponseHeadersPolicyId: !FindInMap [ ResponseHeadersPolicyIds, CORS-with-preflight-and-SecurityHeadersPolicy, Id ]
            ViewerProtocolPolicy: redirect-to-https
    AssetsDns:
      Type: 'AWS::Route53::RecordSet'
      Properties:
        HostedZoneId: ${ssm:/ken/route53/zoneId}
        Name: !Sub 'ken-assets.${ssm:/ken/route53/zoneName}'
        Type: A
        AliasTarget:
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt AssetsCdn.DomainName
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ken-laravel-queue
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 120
